spring.datasource.url=jdbc:mysql://localhost:3306/ki
spring.datasource.username=root
spring.datasource.password=kiran@89
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

keycloak.server-url=http://18.218.205.124:8080
keycloak.realm=kanrealm
keycloak.client-id=kanclient
keycloak.client-secret=F1UxAgwbSsu2hdQUoRUvVS5ZHZcIxSvA
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://18.218.205.124:8080/realms/kanrealm

spring.kafka.bootstrap-servers=localhost:9092
#http://18.218.205.124:9092   
#spring.kafka.listener.auto-startup=false
spring.kafka.consumer.group-id=producer-service
spring.kafka.consumer.auto-offset-reset=earliest


keycloak.masterrealm=master
keycloak.masterclientid=admin-cli
keycloak.username=admin   # Keycloak admin username
keycloak.password=admin   # Keycloak admin password

spring.master-url=http://localhost:8070
#spring.datasource.url=jdbc:mysql://localhost:3306/ki
#spring.datasource.username=root
#spring.datasource.password=kiran@89
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#keycloak.server-url=http://localhost:8080
#keycloak.realm=kanrealm
#keycloak.client-id=kanclient
#keycloak.client-secret=ja1PtGjL4QbMkfVpcgP28z4ohJRRH8QY
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/kanrealm
#spring.kafka.bootstrap-servers=localhost:9092


#keycloak.masterrealm=master
#keycloak.masterclientid=admin-cli
#keycloak.username=admin   # Keycloak admin username
#keycloak.password=admin   # Keycloak admin password







#spring.datasource.url=jdbc:mysql://localhost:3306/ki
#spring.datasource.username=root
#spring.datasource.password=kiran@89
#
#keycloak.server-url=http://localhost:8080
#keycloak.realm=kanrealm
#keycloak.client-id=kanclient
#keycloak.client-secret=ja1PtGjL4QbMkfVpcgP28z4ohJRRH8QY
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/kanrealm
#
#spring.kafka.bootstrap-servers=localhost:9092
