## Outbox insert
#kafka.user.insert=INSERT INTO kafka_user_register (topic, payload, status) VALUES (?, ?, 'PENDING')
#
### Update success
#update.outbox.success=UPDATE kafka_user_register SET status='SUCCESS', last_attempt=NOW() WHERE id=?
##
### Update failure
#update.outbox.failure=UPDATE kafka_user_register SET status='FAILED', retry_count=retry_count+1, last_attempt=NOW() WHERE id=?

## Outbox insert
#kafka.user.insert=INSERT INTO kafka_outbox (topic, payload, status) VALUES (?, ?, 'PENDING')
#
#update.outbox.sent=UPDATE kafka_outbox SET status='SENT', last_attempt=NOW(), updated_at=NOW() WHERE id=?
#
### Update success
#update.outbox.success=UPDATE kafka_outbox SET status='SUCCESS', last_attempt=NOW() WHERE id=?
##
### Update failure
#update.outbox.failure=UPDATE kafka_outbox SET status='FAILED', retry_count=retry_count+1, last_attempt=NOW() WHERE id=?

kafka.user.insert=INSERT INTO kafka_outbox(topic, payload, status) VALUES (?, ?, 'PENDING')
update.outbox.sent=UPDATE kafka_outbox SET status='SENT', updated_at=NOW() WHERE id=?
update.outbox.success=UPDATE kafka_outbox SET status='SUCCESS', updated_at=NOW() WHERE id=?
update.outbox.failed=UPDATE kafka_outbox SET status='FAILED', retry_count=retry_count+1, updated_at=NOW() WHERE id=?
update.outbox.retry="UPDATE kafka_outbox SET retry_count=retry_count+1, updated_at=NOW() WHERE id=?"
#select.outbox.failed=SELECT id, topic, payload FROM kafka_outbox WHERE status='FAILED' AND retry_count < 3

select.outbox.failed=SELECT id, topic, payload, retry_count FROM kafka_outbox WHERE status IN ('FAILED', 'PENDING') AND retry_count < 3 AND ((retry_count = 0 AND TIMESTAMPDIFF(MINUTE, updated_at, NOW()) >= 1) OR(retry_count = 1 AND TIMESTAMPDIFF(MINUTE, updated_at, NOW()) >= 5) OR(retry_count = 2 AND TIMESTAMPDIFF(MINUTE, updated_at, NOW()) >= 15))
update.outbox.reset.permanent.failed=UPDATE kafka_outbox SET status = 'PENDING', retry_count = 0, updated_at = NOW() WHERE status = 'PERMANENTLY_FAILED'
delete.outbox.success=DELETE FROM kafka_outbox WHERE status='SUCCESS' AND TIMESTAMPDIFF(DAY, updated_at, NOW()) > 7
update.outbox.permanant.failed=UPDATE kafka_outbox SET status='PERMANENTLY_FAILED', updated_at=NOW() WHERE status IN ('FAILED', 'PENDING') AND retry_count >= 3
#UPDATE kafka_outbox SET status='FAILED', retry_count=retry_count+1, updated_at=NOW() WHERE id=?